"use strict";

module.exports = {
  Category: ["name", "slug"],
  City: ["name"],
  Content: ["title", "slug"],
  Country: ["name"],
  Course: ["title", "slug"],
  Duration: ["title", "slug"],
  Eligibility: ["title", "slug"],
  Faq: ["question", "answer"],
  Fee: ["title", "currency", "slug"],
  Header: ["label", "slug"],
  Hero: ["name", "page", "title", "badge"],
  Location: ["name"],
  Media: ["name", "fileName", "url"],
  Page: ["title", "slug"],
  PageMeta: ["pageName", "pagePath", "title", "description"],
  PartnerCourse: ["title", "slug"],
  PartnerUniversity: ["name", "slug"],
  Pincode: ["pincode"],
  Rating: ["name", "review"],
  Role: ["name", "des"],
  Sidebar: ["title", "path", "section"],
  SiteSetting: ["siteName", "siteUrl", "gtmId"],
  State: ["name"],
  Subcourse: ["title", "slug"],
  Tenant: ["name", "slug"],
  Theme: ["themeName", "primaryColor", "secondaryColor"],
  University: ["name", "slug"],
  User: ["fullname", "username", "email"],
  Workspace: ["name", "description"],
};
